sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
  - "11"

os:
  - linux
  - osx
  #- windows

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
        addons:
          apt:
            sources:
              - ubuntu-toolchain-r-test
            packages:
              - g++-4.9
        env:
          - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
  # print versions
  - node --version
  - npm --version
  # use g++-4.8 on Linux
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.9; fi
  - "$CXX --version"
  # figure out if we should publish
  - PUBLISH_BINARY=no
  # if we are building a tag then publish
  - echo $TRAVIS_BRANCH
  - echo `git describe --tags --always HEAD`
  - if [[ $TRAVIS_BRANCH == `git describe --tags --always HEAD` ]]; then PUBLISH_BINARY=yes; fi;
  - echo "Are we going to publish a binary? ->" $PUBLISH_BINARY

install:
  # ensure source install works
  - npm install --build-from-source

script:
  - npm test
  # publish on a tag
  - if [[ $PUBLISH_BINARY == yes ]]; then node-pre-gyp package; fi;
  - if [[ $PUBLISH_BINARY == yes ]]; then node-pre-gyp-github publish --release; fi;
  # cleanup
  - node-pre-gyp clean
  # test binary exists
  - if [[ $PUBLISH_BINARY == yes ]]; then npm install --fallback-to-build=false; fi;
